routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::group(['middleware' => 'auth'], function () {
    
    Route::view('dashboard', 'dashboard')->name('dashboard');

    Route::resource('kgbs', \App\Http\Controllers\KgbController::class);
    // Route::resource('histories', \App\Http\Controllers\KgbController::class);
    // Route::resource('mains', \App\Http\Controllers\MainController::class);
    Route::resource('mains', \App\Http\Controllers\MainController::class)->parameters(['mains' => 'kgb']);
});

require __DIR__.'/auth.php';

app/Models/Main.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Main extends Model
{
    use HasFactory;

    protected $fillable = [
        'nip',
        'nama',
        'unit_kerja',
        'last_kgb',
        'next_kgb',
        'golongan',
        'pensiun',
        'reminder',
        'status',
        'p_kgb',
        'n_kgb'
    ];
}

app/Http/Controllers/MainController.php
<?php

namespace App\Http\Controllers;

use App\Models\Kgb;
use App\Models\Main;
use DateTime, DateInterval;
// use Illuminate\Support\Facades\DB;
use Illuminate\Http\Request;

class MainController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        //
        // $mains = DB::table('kgbs')->where('nama', 'Golobok')->get();
        $time = \Carbon\Carbon::now()->format('Y-m');
        error_log($time);

        if (sizeof($request->all()) == 0) {
            $kgbs = kgb::where([
                ['reminder', '!=', NULL],
                [function ($query) use ($request) {
                    if ($time = \Carbon\Carbon::now()->format('Y-m')) {
                        // $time = \Carbon\Carbon::now()->format('Y-m');
                        $time = $query->orWhere('reminder', 'LIKE', $time . '-%%')->get();
                    }
                }]
            ])->orderBy("nama", "asc")->paginate(5);
            error_log("0");
        } else {
            error_log("1");
            $kgbs = kgb::where([
                ['reminder', '!=', NULL],
                [function ($query) use ($request) {
                    if ($last_kgb = $request->last_kgb) {
                        $last_kgb = $query->orWhere('reminder', 'LIKE', $last_kgb . '-%%')->get();
                    }
                }]
            ])->orderBy("nama", "asc")->paginate(5);
        }
        return view('mains.index', compact('kgbs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Main  $main
     * @return \Illuminate\Http\Response
     */
    public function show(Kgb $kgb)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Main  $main
     * @return \Illuminate\Http\Response
     */
    public function edit(Kgb $kgb)
    {
        //
        // error_log(print_r($kgb, true));
        return view('mains.edit', compact('kgb'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Main  $main
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        // error_log("baris eror");
        // $id = $request->input();
        // error_log(print_r($request->all(), true));
        // error_log(print_r($id, true));

        $kgb = Kgb::find($id);
        // error_log(print_r($kgb, true));
        // error_log(print_r($kgb['nama'], true));

        // $input = $request->all();
        // error_log(print_r($input, true));

        $tgl = substr($kgb['last_kgb'], 8, 2);
        $bln = substr($kgb['last_kgb'], 5, 2);
        $thn = substr($kgb['last_kgb'], 0, 4);
        $last_kgb = ((int)$thn + 2) . "-" . $bln . "-" . $tgl;

        $tgl = substr($kgb['next_kgb'], 8, 2);
        $bln = substr($kgb['next_kgb'], 5, 2);
        $thn = substr($kgb['next_kgb'], 0, 4);
        $next_kgb = ((int)$thn + 2) . "-" . $bln . "-" . $tgl;

        $tgl = substr($kgb['reminder'], 8, 2);
        $bln = substr($kgb['reminder'], 5, 2);
        $thn = substr($kgb['reminder'], 0, 4);
        $reminder = ((int)$thn + 2) . "-" . $bln . "-" . $tgl;

        $collection = array(
            'next_kgb' => $next_kgb, 'reminder' => $reminder, 'last_kgb' => $last_kgb
        );

        $data = array_merge($request->all(), $collection);
        error_log(print_r($data, true));

        $kgb->update($data);

        return redirect()->route('mains.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Main  $main
     * @return \Illuminate\Http\Response
     */
    public function destroy(Kgb $kgb)
    {
        //
        // error_log(print_r($kgb->all(), true));

        // $kgb->delete();
        return redirect()->route('mains.index');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.app');
    }
}

resources/views/mains/edit.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Validasi Data') }}
        </h2>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <form method="POST" action="{{ route('mains.update', $kgb->id) }}" autocomplete="off">
                        @method('PUT')
                        @csrf
                        <div class="fixed z-10 inset-0 overflow-y-auto" aria-labelledby="modal-title" role="dialog" aria-modal="true">
                            <div class="flex items-end justify-center min-h-screen pt-4 px-4 pb-20 text-center sm:block sm:p-0">
                                <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity" aria-hidden="true">
                                    <!-- This element is to trick the browser into centering the modal contents. -->
                                    <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;
                                        <div class="inline-block align-bottom bg-white rounded-lg text-left overflow-hidden shadow-xl transform transition-all sm:my-8 sm:align-middle sm:max-w-lg sm:w-full">
                                            <div class="bg-white px-4 pt-5 pb-4 sm:p-6 sm:pb-4">
                                                <div class="sm:flex sm:items-start">
                                                    <div class="mt-3 text-center sm:mt-0 sm:ml-4 sm:text-left">
                                                        <h3 class="text-lg leading-6 font-medium text-gray-900" id="modal-title">
                                                            Validasi Berkas
                                                        </h3>
                                                        <div class="mt-2">
                                                            <table class="min-w-full divide-y divide-gray-200">
                                                                <thead class="bg-gray-50">
                                                                    <tr>
                                                                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                                            NIP
                                                                        </th>
                                                                        <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                                            NAMA
                                                                        </th>
                                                                    </tr>
                                                                </thead>
                                                                <tbody class="bg-white divide-y divide-gray-200">
                                                                    <tr>
                                                                        <td class="px-6 py-4 whitespace-nowrap">
                                                                            <div class="flex items-center">
                                                                                {{ $kgb->nip}}
                                                                            </div>
                                                                        </td>
                                                                        <td class="px-6 py-4 whitespace-nowrap">
                                                                            <div class="flex items-center">
                                                                                {{ $kgb->nama}}
                                                                            </div>
                                                                        </td>
                                                                    </tr>
                                                                </tbody>
                                                            </table>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="bg-gray-50 px-4 py-3 sm:px-6 sm:flex sm:flex-row-reverse">
                                                <button type="submit" class="w-full inline-flex justify-center rounded-md border border-transparent shadow-sm px-4 py-2 bg-blue-600 text-base font-medium text-white hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-red-500 sm:ml-3 sm:w-auto sm:text-sm">
                                                    Validasi
                                                </button>
                                                <button type="button" class="w-full inline-flex justify-center rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-base font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 sm:mt-0 sm:ml-3 sm:w-auto sm:text-sm">
                                                    <a href="{{ route('mains.index') }}">
                                                        Cancel
                                                    </a>
                                                </button>
                                            </div>
                                        </div>
                                    </span>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>

resources/views/mains/index.blade.php
<x-app-layout>
    <x-slot name="header">
        <h2 class="font-semibold text-xl text-gray-800 leading-tight">
            {{ __('Data Yang Belum Melakukan KGB') }}
        </h2>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.5.0/css/bootstrap.min.css" />
        <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/css/bootstrap-datepicker.css" rel="stylesheet">
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.5.6/jspdf.plugin.autotable.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.5.0/js/bootstrap-datepicker.js"></script>
    </x-slot>

    <div class="py-12">
        <div class="max-w-7xl mx-auto sm:px-6 lg:px-8">
            <div class="bg-white overflow-hidden shadow-sm sm:rounded-lg">
                <div class="p-6 bg-white border-b border-gray-200">
                    <div class="grid grid-cols-2 gap-6">
                        <div class="grid grid-rows-1 gap-6">
                            <form action="{{ route('mains.index') }}" method="GET" role="search" autocomplete="off">
                                <div class="input-group">
                                    <div class="mt-1 flex rounded-md shadow-sm">
                                        <span class="inline-flex items-center px-3 rounded-l-md border border-r-0 border-gray-300 bg-gray-50 text-gray-500 text-sm">
                                            Bulan, Tahun :
                                        </span>
                                        <input id="last_kgb" class="date block focus:ring-indigo-500 focus:border-indigo-500 flex-1 rounded-none rounded-r-md sm:text-sm border-gray-300" type="text" name="last_kgb">
                                        <script type="text/javascript">
                                            $('.date').datepicker({
                                                format: "yyyy-mm",
                                                startView: "months",
                                                minViewMode: "months",
                                                // todayHighlight: true,
                                                autoclose: true,
                                            });
                                        </script>
                                    </div>
                                    <x-button type="submit" class="ml-1 mt-1">
                                        Cari
                                    </x-button>
                                </div>
                            </form>
                        </div>
                        <div class="grid grid-rows-1 gap-6 ">
                            <a>
                                <x-button onclick="generate()" type="button" class="ml-1 mt-1 float-right text-white bg-indigo-600 hover:bg-indigo-700">
                                    Export to PDF
                                </x-button>
                            </a>
                        </div>
                    </div>
                    <br>
                    <div class="flex flex-col">
                        <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                                    <table id="simple_table" class="min-w-full divide-y divide-gray-200">
                                        <thead class="bg-gray-50">
                                            <tr>
                                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                    NIP
                                                </th>
                                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                    Name
                                                </th>
                                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                    Reminder
                                                </th>
                                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                                    KGB Berikutnya
                                                </th>
                                                <th scope="col" class="relative px-6 py-3">
                                                    <span class="sr-only">Action KGB</span>
                                                </th>
                                            </tr>
                                        </thead>
                                        <tbody class="bg-white divide-y divide-gray-200">
                                            @foreach ($kgbs as $kgb)
                                            <tr>
                                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                                    {{ $kgb->nip }}
                                                </td>
                                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                                    {{ strtoupper($kgb->nama) }}
                                                </td>
                                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                                    <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                                        {{ $kgb->reminder }}
                                                    </span>
                                                </td>
                                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                                    {{ $kgb->next_kgb }}
                                                </td>
                                                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                                    <a href="{{ route('mains.edit', $kgb) }}" class="bg-white hover:bg-gray-100 text-gray-800 font-semibold py-2 px-4 border border-gray-400 rounded shadow">
                                                        Validasi
                                                    </a>
                                                </td>
                                            </tr>
                                            @endforeach
                                        </tbody>
                                    </table>
                                </div>
                                <div class="mt-4">
                                    {{ $kgbs->links() }}
                                </div>
                                <script type="text/javascript">
                                    function generate() {
                                        var doc = new jsPDF('p', 'pt', 'letter');
                                        var htmlstring = '';
                                        var tempVarToCheckPageHeight = 0;
                                        var pageHeight = 0;
                                        pageHeight = doc.internal.pageSize.height;
                                        specialElementHandlers = {
                                            // element with id of "bypass" - jQuery style selector  
                                            '#bypassme': function(element, renderer) {
                                                // true = "handled elsewhere, bypass text extraction"  
                                                return true
                                            }
                                        };
                                        margins = {
                                            top: 150,
                                            bottom: 60,
                                            left: 40,
                                            right: 40,
                                            width: 600
                                        };
                                        var today = new Date();
                                        // var date = today.getFullYear() + '-' + (today.getMonth() + 1) + '-' + today.getDate();
                                        var date = today.getDate() + '-' + (today.getMonth() + 1) + '-' + today.getFullYear();
                                        var y = 20;
                                        doc.setLineWidth(2);
                                        doc.text(310, 35, "Data Yang belum Validasi Berkas KGB \n " + date + '\n', {
                                            align: 'center'
                                        });
                                        doc.setfon
                                        doc.autoTable({
                                            html: '#simple_table',
                                            startY: 70,
                                            theme: 'grid',
                                            // columnStyles: {
                                            //     0: {
                                            //         cellWidth: 180,
                                            //     },
                                            //     1: {
                                            //         cellWidth: 180,
                                            //     },
                                            //     2: {
                                            //         cellWidth: 180,
                                            //     }
                                            // },
                                            // styles: {
                                            //     minCellHeight: 40
                                            // }
                                        })
                                        doc.save('KGB ' + date + '.pdf');
                                    }
                                </script>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</x-app-layout>